### ISSUE TITLE
Progress Report Download Large Files (>2GB)

### ISSUE THREAD

**Issue by dwschmid** [DigitalMediaServer/NSIS-INetC-plugin#4] opened 2019-11-25 20:45 UTC
The INetC plugin seems to report wrong progress when downloading files that are larger than 2GB. As long as more than 2GB remain to be downloaded the "Remaining Time" is reported far too big. Also, the % progress is wrong, reported as negative numbers that go beyond -100%.

**Comment by Nadahar** [comment] 2019-11-25 20:51
Sounds like a 32 bit int is used where a 64 bit should be. Have you experienced it using this plugin or the official/original INetC plugin? The problem is probably with both, but if you're using the official/original, a fix here won't help.

**Comment by dwschmid** [comment] 2019-11-25 20:58
I have it with both. The reason I came here was in the hope that this version does not have this problem.

**Comment by Nadahar** [comment] 2019-11-25 21:23
I haven't changed the part of the code that calculates the progress, so the problem is very likely identical with both versions.

It should be fixed, and probably isn't even very hard to fix, although it goes many months between every time I touch C++, so I have to "re-familiarize myself" with the whole environment every time. Also, types in NSIS plugins (there are some restrictions imposed by NSIS) is somewhat of an enigma to me. That said, it probably shouldn't take too long once I first sit down with it.

Have you tested if it works correctly if you use the 64-bit version of the plugin? That requires that your NSIS build is 64-bit as well though, so it's not really a very good workaround. I would assume that whatever type is used for this is "longer" (bitwise) in the 64-bit version.

**Comment by dwschmid** [comment] 2019-11-26 07:33
I use NSIS 3.04, cannot figure out if it is 32 or 64bit, from the release notes definitely looks like it should support 64bit variables. Would be great if you find the time to look into this. BTW: the particular file that I try to download is the Matlab runtime. I post the link below so you have a test case (should you need one).
[http://ssd.mathworks.com/supportfiles/downloads/R2019b/Release/1/deployment_files/installer/complete/win64/MATLAB_Runtime_R2019b_Update_1_win64.zip](url)

**Comment by Nadahar** [comment] 2019-11-26 14:45
You can make NSIS make 32 bit or 64 bit installers. If you make a 64 bit installer, you'd have to use 64 bit versions of all plugins etc. That should make it work as it is.

The reason I'm saying it's probably not desirable, is that a 64 bit installer won't run on a 32 bit OS. It would thus limit which Windows versions your application could be installed on to only 64 bit versions. If your application only runs on 64 bit OSes, this shouldn't be a problem though.

**Comment by dwschmid** [comment] 2019-11-27 11:37
Yes, the best would be if it would work on 32 bit installers too. Would be great if you would find time to look into this.

**Comment by dwschmid** [comment] 2020-07-16 09:53
I looked into this issue again. Turns out it was solved in 2015 by LoRd_MuldeR, see thread:
http://forums.winamp.com/showthread.php?t=381592
His inetc.signed-int-overflow-fix.V2.zip displays download progress of >2GB files properly (probably restricted to <4GB). 
Would be great to have this change implemented here.

**Comment by Nadahar** [comment] 2020-07-17 00:10
It isn't a fix for the 32 bit issue, it's only a switch to unsigned instead of signed 32 bit integer from what I can understand. That will only mitigate the problem slightly, a proper fix would be to use a 64 bit integer. It seems that this isn't possible because CRT is excluded, but that sounds like just the type of "weirdness" I've fought with a lot already in this plugin. I'm not nearly experienced enough with C/C++ to fight issues like that, I have no idea where to even start. I just had to conclude for myself that a lot of types are unavailable, for reasons I don't understand, and simply stick to the types that I could find being in use somewhere already.

One should think there would be a way to handle 64 bit integers even in an "old" 32-bit environment, but it seems like it requires much more knowledge than I have to do.

**Comment by dwschmid** [comment] 2020-07-17 06:40
I agree, this is not solution that will solve the problem for any file size, but at least the downloads between 2GB and 4GB will show proper progress. That is still twice the size range and happens to fix my particular problem (2.6GB runtime download). Progress indication with negative numbers and percentages >100% was driving me nuts.

**Comment by Nadahar** [comment] 2020-07-17 13:55
I've tried to look a bit into this, and it seems to me that the `aulldiv` assembler source in the link might actually handle 64 bit integers. I'm not sure though, as I only understand some of the assembler instructions so I don't get a proper understanding. If not, I think [this](https://gist.github.com/mmozeiko/6a365d6c483fc721b63a#file-win32_crt_math-cpp) should do it.

I've also found that the size is retrieved as a string from the Windows API, so there should be no 32 bit limitation there. A new "string to integer" conversion routine would have to be written that could handle 64 bit integers, but I don't think that should be too difficult either.

After calculating the percentage, we're well within the 32 bit limits so passing this on further should be no problem. There might be another issue converting it back to string to display "downloaded size", but I haven't looked into whether this is easy or hard to solve.

The major hurdle for me is that I just can't wrap my head around the type system and the limitations imposed by NSIS (the lack of the "standard libraries" like CRT). So, I have no idea how to get a 64 bit integer type, signed or unsigned (either would do). It would also have to remain 64 bit both when compiled as 32 bit and 64 bit - which can often be a challenge as many of these types magically change width with the "native int".

If I had a 64 bit integer type that I know would stay 64 bit and work under all circumstances, I think I could figure the rest out, but I really have no idea how to find this. `DWORD` (32 bit used today) seems to be defined in `WinDef.h`, so I assume that all types defined there are "safe" to use. I can find no 64 bit integer type there though. I've found both `DWORDLONG` and `ULONGLONG`, which both seems to be 64 bit, in `WinNT.h`, but I have no idea if any of those are safe to use. Similarly, I've found `DWORD64` and `ULONG64` in `BaseTsd.h`, but again I have no idea if I can use any of them.

Without figuring out the type stuff, I'm afraid I'm a bit lost. This is the only project I have using C/C++, so it's not very tempting to take a deep dive investing days on getting to know the type system well enough to figure it out. There must be lots of people out there that could answer this almost without having to think..

**Comment by dwschmid** [comment] 2020-07-17 14:19
Unfortunately, I'm not part of the group of people that have the technical know-how to answer the questions that you raise.  I also understand that you cannot invest much time into this. For my projects, I'll use the version by LoRd_MuldeR as it works as expected for my cases. Maybe somebody else might have the same problem in the future and find this exchange useful or even fix it properly. 
Thanks for looking into this!

**Comment by pjpuchyr** [comment] 2022-03-14 05:50
I've solved this problem trivially.  The only issue with large files is in the MulDiv calls in function progress_callback.  MulDiv arguments are all 32 bit ints.  When the file size fs exceeds 2 GB, MulDiv messes up the percent or fraction calculation.   The solution is simply to divide the cnt and fs variables by 1024 in both the calls to MulDiv when fs is greater than (2^31)/100.

I'm new to providing open source fixes.  Should I just push my changes up to GitHub, or is there some procedure that needs to be followed?

**Comment by Nadahar** [comment] 2022-03-14 07:26
@pjpuchyr That's great! The "standard GitHub way" to do it is to create a "Pull Request" (PR). The way you do that is to first fork this repository and push the change to your own fork. If you have already cloned this repository directly, you can just add a second "remote" to your local repository pointing to your fork. Once you have pushed the change to your fork, you open the GitHub page and go to your fork, and it should say "Create a pull request" on top. One thing to watch out for the first time you do it, is that you shouldn't push your changed to the `master` branch in your fork, since the PR will be updated if you make changes to the branch. Instead, you should make a branch for said fix, e.g "LargeDownloads" and push the changes there.

There.s a decent explanation of the process here: https://gist.github.com/Chaser324/ce0505fbed06b947d962
Depending on how well you know Git this may or may not be too much for you. If you prefer, you can just create a patch with your local git client and upload the patch as a zipped attachment here, and I'll apply it.

**Comment by rollingmoai** [comment] 2022-03-16 02:12
The best solution here is to use [NSCurl](https://github.com/negrutiu/nsis-nscurl) which is implemented on top of the modern libcurl and has way more features.

**Comment by Nadahar** [comment] 2022-03-16 20:26
@itsmeboy0 I haven't tried [NSCurl](https://github.com/negrutiu/nsis-nscurl) so I don't know how it actually works, but I must say that it sounds like a much better approach :+1: 

The problem with this plugin is that it's based on Microsoft's WinINet, which is bad for so many reasons. It uses parts of Internet Explorer internally, which means that IE configuration will impact how the plugin works (proxy settings for example). It is also limited by the capabilities of the IE version installed, which means that Windows XP computers can't access HTTPS addresses because Windows XP doesn't support TLS 1.2 (which has become the current "standard").

If there are no major issues with [NSCurl](https://github.com/negrutiu/nsis-nscurl), I'd say it pretty much renders this plugin pointless.

**Comment by rollingmoai** [comment] 2022-03-17 01:20
> If there are no major issues with [NSCurl](https://github.com/negrutiu/nsis-nscurl), I'd say it pretty much renders this plugin pointless.

I'd say I have been using it for a long time, and I haven't encountered an issue yet. Maybe add a note in the README pointing to NSCurl.

**Comment by Nadahar** [comment] 2022-03-28 15:58
This should be fixed with #8

**Closed as completed by Nadahar** 2022-03-28 15:58 UTC
